//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSClient.WSConsumo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSConsumo.ServicioWebSoap")]
    public interface ServicioWebSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento etiqueta del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarConsumo", ReplyAction="*")]
        WSClient.WSConsumo.ModificarConsumoResponse ModificarConsumo(WSClient.WSConsumo.ModificarConsumoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarConsumo", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.WSConsumo.ModificarConsumoResponse> ModificarConsumoAsync(WSClient.WSConsumo.ModificarConsumoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MostrarUsuariosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarUsuarios", ReplyAction="*")]
        WSClient.WSConsumo.MostrarUsuariosResponse MostrarUsuarios(WSClient.WSConsumo.MostrarUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarUsuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.WSConsumo.MostrarUsuariosResponse> MostrarUsuariosAsync(WSClient.WSConsumo.MostrarUsuariosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento email del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarUbicacionesDelUsuario", ReplyAction="*")]
        WSClient.WSConsumo.MostrarUbicacionesDelUsuarioResponse MostrarUbicacionesDelUsuario(WSClient.WSConsumo.MostrarUbicacionesDelUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostrarUbicacionesDelUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.WSConsumo.MostrarUbicacionesDelUsuarioResponse> MostrarUbicacionesDelUsuarioAsync(WSClient.WSConsumo.MostrarUbicacionesDelUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento etiqueta del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsumoEnEsteInstante", ReplyAction="*")]
        WSClient.WSConsumo.ConsumoEnEsteInstanteResponse ConsumoEnEsteInstante(WSClient.WSConsumo.ConsumoEnEsteInstanteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsumoEnEsteInstante", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.WSConsumo.ConsumoEnEsteInstanteResponse> ConsumoEnEsteInstanteAsync(WSClient.WSConsumo.ConsumoEnEsteInstanteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarConsumoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarConsumo", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.WSConsumo.ModificarConsumoRequestBody Body;
        
        public ModificarConsumoRequest() {
        }
        
        public ModificarConsumoRequest(WSClient.WSConsumo.ModificarConsumoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarConsumoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double consumo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string etiqueta;
        
        public ModificarConsumoRequestBody() {
        }
        
        public ModificarConsumoRequestBody(double consumo, string etiqueta) {
            this.consumo = consumo;
            this.etiqueta = etiqueta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarConsumoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarConsumoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.WSConsumo.ModificarConsumoResponseBody Body;
        
        public ModificarConsumoResponse() {
        }
        
        public ModificarConsumoResponse(WSClient.WSConsumo.ModificarConsumoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ModificarConsumoResponseBody {
        
        public ModificarConsumoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarUsuarios", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.WSConsumo.MostrarUsuariosRequestBody Body;
        
        public MostrarUsuariosRequest() {
        }
        
        public MostrarUsuariosRequest(WSClient.WSConsumo.MostrarUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MostrarUsuariosRequestBody {
        
        public MostrarUsuariosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarUsuariosResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.WSConsumo.MostrarUsuariosResponseBody Body;
        
        public MostrarUsuariosResponse() {
        }
        
        public MostrarUsuariosResponse(WSClient.WSConsumo.MostrarUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarUsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.WSConsumo.ArrayOfString MostrarUsuariosResult;
        
        public MostrarUsuariosResponseBody() {
        }
        
        public MostrarUsuariosResponseBody(WSClient.WSConsumo.ArrayOfString MostrarUsuariosResult) {
            this.MostrarUsuariosResult = MostrarUsuariosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarUbicacionesDelUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarUbicacionesDelUsuario", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.WSConsumo.MostrarUbicacionesDelUsuarioRequestBody Body;
        
        public MostrarUbicacionesDelUsuarioRequest() {
        }
        
        public MostrarUbicacionesDelUsuarioRequest(WSClient.WSConsumo.MostrarUbicacionesDelUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarUbicacionesDelUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public MostrarUbicacionesDelUsuarioRequestBody() {
        }
        
        public MostrarUbicacionesDelUsuarioRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MostrarUbicacionesDelUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MostrarUbicacionesDelUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.WSConsumo.MostrarUbicacionesDelUsuarioResponseBody Body;
        
        public MostrarUbicacionesDelUsuarioResponse() {
        }
        
        public MostrarUbicacionesDelUsuarioResponse(WSClient.WSConsumo.MostrarUbicacionesDelUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MostrarUbicacionesDelUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.WSConsumo.ArrayOfString MostrarUbicacionesDelUsuarioResult;
        
        public MostrarUbicacionesDelUsuarioResponseBody() {
        }
        
        public MostrarUbicacionesDelUsuarioResponseBody(WSClient.WSConsumo.ArrayOfString MostrarUbicacionesDelUsuarioResult) {
            this.MostrarUbicacionesDelUsuarioResult = MostrarUbicacionesDelUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsumoEnEsteInstanteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsumoEnEsteInstante", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.WSConsumo.ConsumoEnEsteInstanteRequestBody Body;
        
        public ConsumoEnEsteInstanteRequest() {
        }
        
        public ConsumoEnEsteInstanteRequest(WSClient.WSConsumo.ConsumoEnEsteInstanteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsumoEnEsteInstanteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string etiqueta;
        
        public ConsumoEnEsteInstanteRequestBody() {
        }
        
        public ConsumoEnEsteInstanteRequestBody(string etiqueta) {
            this.etiqueta = etiqueta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsumoEnEsteInstanteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsumoEnEsteInstanteResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.WSConsumo.ConsumoEnEsteInstanteResponseBody Body;
        
        public ConsumoEnEsteInstanteResponse() {
        }
        
        public ConsumoEnEsteInstanteResponse(WSClient.WSConsumo.ConsumoEnEsteInstanteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsumoEnEsteInstanteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double ConsumoEnEsteInstanteResult;
        
        public ConsumoEnEsteInstanteResponseBody() {
        }
        
        public ConsumoEnEsteInstanteResponseBody(double ConsumoEnEsteInstanteResult) {
            this.ConsumoEnEsteInstanteResult = ConsumoEnEsteInstanteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioWebSoapChannel : WSClient.WSConsumo.ServicioWebSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWebSoapClient : System.ServiceModel.ClientBase<WSClient.WSConsumo.ServicioWebSoap>, WSClient.WSConsumo.ServicioWebSoap {
        
        public ServicioWebSoapClient() {
        }
        
        public ServicioWebSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWebSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.WSConsumo.ModificarConsumoResponse WSClient.WSConsumo.ServicioWebSoap.ModificarConsumo(WSClient.WSConsumo.ModificarConsumoRequest request) {
            return base.Channel.ModificarConsumo(request);
        }
        
        public void ModificarConsumo(double consumo, string etiqueta) {
            WSClient.WSConsumo.ModificarConsumoRequest inValue = new WSClient.WSConsumo.ModificarConsumoRequest();
            inValue.Body = new WSClient.WSConsumo.ModificarConsumoRequestBody();
            inValue.Body.consumo = consumo;
            inValue.Body.etiqueta = etiqueta;
            WSClient.WSConsumo.ModificarConsumoResponse retVal = ((WSClient.WSConsumo.ServicioWebSoap)(this)).ModificarConsumo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.WSConsumo.ModificarConsumoResponse> WSClient.WSConsumo.ServicioWebSoap.ModificarConsumoAsync(WSClient.WSConsumo.ModificarConsumoRequest request) {
            return base.Channel.ModificarConsumoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.WSConsumo.ModificarConsumoResponse> ModificarConsumoAsync(double consumo, string etiqueta) {
            WSClient.WSConsumo.ModificarConsumoRequest inValue = new WSClient.WSConsumo.ModificarConsumoRequest();
            inValue.Body = new WSClient.WSConsumo.ModificarConsumoRequestBody();
            inValue.Body.consumo = consumo;
            inValue.Body.etiqueta = etiqueta;
            return ((WSClient.WSConsumo.ServicioWebSoap)(this)).ModificarConsumoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.WSConsumo.MostrarUsuariosResponse WSClient.WSConsumo.ServicioWebSoap.MostrarUsuarios(WSClient.WSConsumo.MostrarUsuariosRequest request) {
            return base.Channel.MostrarUsuarios(request);
        }
        
        public WSClient.WSConsumo.ArrayOfString MostrarUsuarios() {
            WSClient.WSConsumo.MostrarUsuariosRequest inValue = new WSClient.WSConsumo.MostrarUsuariosRequest();
            inValue.Body = new WSClient.WSConsumo.MostrarUsuariosRequestBody();
            WSClient.WSConsumo.MostrarUsuariosResponse retVal = ((WSClient.WSConsumo.ServicioWebSoap)(this)).MostrarUsuarios(inValue);
            return retVal.Body.MostrarUsuariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.WSConsumo.MostrarUsuariosResponse> WSClient.WSConsumo.ServicioWebSoap.MostrarUsuariosAsync(WSClient.WSConsumo.MostrarUsuariosRequest request) {
            return base.Channel.MostrarUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.WSConsumo.MostrarUsuariosResponse> MostrarUsuariosAsync() {
            WSClient.WSConsumo.MostrarUsuariosRequest inValue = new WSClient.WSConsumo.MostrarUsuariosRequest();
            inValue.Body = new WSClient.WSConsumo.MostrarUsuariosRequestBody();
            return ((WSClient.WSConsumo.ServicioWebSoap)(this)).MostrarUsuariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.WSConsumo.MostrarUbicacionesDelUsuarioResponse WSClient.WSConsumo.ServicioWebSoap.MostrarUbicacionesDelUsuario(WSClient.WSConsumo.MostrarUbicacionesDelUsuarioRequest request) {
            return base.Channel.MostrarUbicacionesDelUsuario(request);
        }
        
        public WSClient.WSConsumo.ArrayOfString MostrarUbicacionesDelUsuario(string email) {
            WSClient.WSConsumo.MostrarUbicacionesDelUsuarioRequest inValue = new WSClient.WSConsumo.MostrarUbicacionesDelUsuarioRequest();
            inValue.Body = new WSClient.WSConsumo.MostrarUbicacionesDelUsuarioRequestBody();
            inValue.Body.email = email;
            WSClient.WSConsumo.MostrarUbicacionesDelUsuarioResponse retVal = ((WSClient.WSConsumo.ServicioWebSoap)(this)).MostrarUbicacionesDelUsuario(inValue);
            return retVal.Body.MostrarUbicacionesDelUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.WSConsumo.MostrarUbicacionesDelUsuarioResponse> WSClient.WSConsumo.ServicioWebSoap.MostrarUbicacionesDelUsuarioAsync(WSClient.WSConsumo.MostrarUbicacionesDelUsuarioRequest request) {
            return base.Channel.MostrarUbicacionesDelUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.WSConsumo.MostrarUbicacionesDelUsuarioResponse> MostrarUbicacionesDelUsuarioAsync(string email) {
            WSClient.WSConsumo.MostrarUbicacionesDelUsuarioRequest inValue = new WSClient.WSConsumo.MostrarUbicacionesDelUsuarioRequest();
            inValue.Body = new WSClient.WSConsumo.MostrarUbicacionesDelUsuarioRequestBody();
            inValue.Body.email = email;
            return ((WSClient.WSConsumo.ServicioWebSoap)(this)).MostrarUbicacionesDelUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.WSConsumo.ConsumoEnEsteInstanteResponse WSClient.WSConsumo.ServicioWebSoap.ConsumoEnEsteInstante(WSClient.WSConsumo.ConsumoEnEsteInstanteRequest request) {
            return base.Channel.ConsumoEnEsteInstante(request);
        }
        
        public double ConsumoEnEsteInstante(string etiqueta) {
            WSClient.WSConsumo.ConsumoEnEsteInstanteRequest inValue = new WSClient.WSConsumo.ConsumoEnEsteInstanteRequest();
            inValue.Body = new WSClient.WSConsumo.ConsumoEnEsteInstanteRequestBody();
            inValue.Body.etiqueta = etiqueta;
            WSClient.WSConsumo.ConsumoEnEsteInstanteResponse retVal = ((WSClient.WSConsumo.ServicioWebSoap)(this)).ConsumoEnEsteInstante(inValue);
            return retVal.Body.ConsumoEnEsteInstanteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.WSConsumo.ConsumoEnEsteInstanteResponse> WSClient.WSConsumo.ServicioWebSoap.ConsumoEnEsteInstanteAsync(WSClient.WSConsumo.ConsumoEnEsteInstanteRequest request) {
            return base.Channel.ConsumoEnEsteInstanteAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.WSConsumo.ConsumoEnEsteInstanteResponse> ConsumoEnEsteInstanteAsync(string etiqueta) {
            WSClient.WSConsumo.ConsumoEnEsteInstanteRequest inValue = new WSClient.WSConsumo.ConsumoEnEsteInstanteRequest();
            inValue.Body = new WSClient.WSConsumo.ConsumoEnEsteInstanteRequestBody();
            inValue.Body.etiqueta = etiqueta;
            return ((WSClient.WSConsumo.ServicioWebSoap)(this)).ConsumoEnEsteInstanteAsync(inValue);
        }
    }
}
