//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.TFG.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bateria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bateria()
        {
            this.Cargas = new HashSet<Carga>();
            this.SeEncuentras = new HashSet<SeEncuentra>();
            this.Suministras = new HashSet<Suministra>();
        }
    
        public long bateriaId { get; set; }
        public long ubicacionId { get; set; }
        public long usuarioId { get; set; }
        public double precioMedio { get; set; }
        public double kwHAlmacenados { get; set; }
        public double almacenajeMaximoKwH { get; set; }
        public System.DateTime fechaDeAdquisicion { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public double ratioCarga { get; set; }
        public double ratioCompra { get; set; }
        public double ratioUso { get; set; }
        public Nullable<long> estadoBateria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carga> Cargas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeEncuentra> SeEncuentras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Suministra> Suministras { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
