//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.TFG.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumo
    {
        public long consumoId { get; set; }
        public long ubicacionId { get; set; }
        public Nullable<double> kwCargados { get; set; }
        public Nullable<double> kwSuministrados { get; set; }
        public Nullable<double> kwRed { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan horaIni { get; set; }
        public Nullable<System.TimeSpan> horaFin { get; set; }
        public double consumoActual { get; set; }
    
        public virtual Ubicacion Ubicacion { get; set; }
    }
}
