//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.TFG.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeEncuentra
    {
        public long seEncuentraId { get; set; }
        public System.TimeSpan horaIni { get; set; }
        public Nullable<System.TimeSpan> horaFin { get; set; }
        public System.DateTime fecha { get; set; }
        public long bateriaId { get; set; }
        public long estadoId { get; set; }
    
        public virtual Bateria Bateria { get; set; }
        public virtual Estado Estado { get; set; }
    }
}
