//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    public partial class Ubicacion
    {
        public Ubicacion()
        {
            this.Baterias = new HashSet<Bateria>();
        }
    
        public long ubicacionId { get; set; }
        public long codigoPostal { get; set; }
        public string localidad { get; set; }
        public string calle { get; set; }
        public long portal { get; set; }
        public long numero { get; set; }
    
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_BATERIA_UBICACION
        /// </summary>
        public virtual ICollection<Bateria> Baterias { get; set; }
    
    	/// <summary>
    	/// A hash code for this instance, suitable for use in hashing algorithms and data structures 
    	/// like a hash table. It uses the Josh Bloch implementation from "Effective Java"
        /// Primary key of entity is not included in the hash calculation to avoid errors
    	/// with Entity Framework creation of key values.
    	/// </summary>
    	/// <returns>
    	/// Returns a hash code for this instance.
    	/// </returns>
    	public override int GetHashCode()
    	{
    	    unchecked
    	    {
    			int multiplier = 31;
    			int hash = GetType().GetHashCode();
    
    			hash = hash * multiplier + codigoPostal.GetHashCode();
    			hash = hash * multiplier + (localidad == null ? 0 : localidad.GetHashCode());
    			hash = hash * multiplier + (calle == null ? 0 : calle.GetHashCode());
    			hash = hash * multiplier + portal.GetHashCode();
    			hash = hash * multiplier + numero.GetHashCode();
    
    			return hash;
    	    }
    
    	}
        
        /// <summary>
        /// Compare this object against another instance using a value approach (field-by-field) 
        /// </summary>
        /// <remarks>See http://www.loganfranken.com/blog/687/overriding-equals-in-c-part-1/ for detailed info </remarks>
    	public override bool Equals(object obj)
    	{
    
            if (ReferenceEquals(null, obj)) return false;        // Is Null?
            if (ReferenceEquals(this, obj)) return true;         // Is same object?
            if (obj.GetType() != this.GetType()) return false;   // Is same type?
    	    
            Ubicacion target = obj as Ubicacion;
    
    		return true
               &&  (this.ubicacionId == target.ubicacionId )       
               &&  (this.codigoPostal == target.codigoPostal )       
               &&  (this.localidad == target.localidad )       
               &&  (this.calle == target.calle )       
               &&  (this.portal == target.portal )       
               &&  (this.numero == target.numero )       
               ;
    
        }
    
    
    	public static bool operator ==(Ubicacion  objA, Ubicacion  objB)
        {
            // Check if the objets are the same Ubicacion entity
            if(Object.ReferenceEquals(objA, objB))
                return true;
      
            return objA.Equals(objB);
    }
    
    
    	public static bool operator !=(Ubicacion  objA, Ubicacion  objB)
        {
            return !(objA == objB);
        }
    
    
        /// <summary>
        /// Returns a <see cref="T:System.String"></see> that represents the 
        /// current <see cref="T:System.Object"></see>.
        /// </summary>
        /// <returns>
        /// A <see cref="T:System.String"></see> that represents the current 
        /// <see cref="T:System.Object"></see>.
        /// </returns>
    	public override String ToString()
    	{
    	    StringBuilder strUbicacion = new StringBuilder();
    
    		strUbicacion.Append("[ ");
           strUbicacion.Append(" ubicacionId = " + ubicacionId + " | " );       
           strUbicacion.Append(" codigoPostal = " + codigoPostal + " | " );       
           strUbicacion.Append(" localidad = " + localidad + " | " );       
           strUbicacion.Append(" calle = " + calle + " | " );       
           strUbicacion.Append(" portal = " + portal + " | " );       
           strUbicacion.Append(" numero = " + numero + " | " );       
            strUbicacion.Append("] ");    
    
    		return strUbicacion.ToString();
        }
    
    
    }
}
