//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Baterias = new HashSet<Bateria>();
        }
    
        public long usuarioId { get; set; }
        public string nombre { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public string email { get; set; }
        public string contraseña { get; set; }
        public string telefono { get; set; }
    
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_BATERIA_USUARIO
        /// </summary>
        public virtual ICollection<Bateria> Baterias { get; set; }
    
    	/// <summary>
    	/// A hash code for this instance, suitable for use in hashing algorithms and data structures 
    	/// like a hash table. It uses the Josh Bloch implementation from "Effective Java"
        /// Primary key of entity is not included in the hash calculation to avoid errors
    	/// with Entity Framework creation of key values.
    	/// </summary>
    	/// <returns>
    	/// Returns a hash code for this instance.
    	/// </returns>
    	public override int GetHashCode()
    	{
    	    unchecked
    	    {
    			int multiplier = 31;
    			int hash = GetType().GetHashCode();
    
    			hash = hash * multiplier + (nombre == null ? 0 : nombre.GetHashCode());
    			hash = hash * multiplier + (apellido1 == null ? 0 : apellido1.GetHashCode());
    			hash = hash * multiplier + (apellido2 == null ? 0 : apellido2.GetHashCode());
    			hash = hash * multiplier + (email == null ? 0 : email.GetHashCode());
    			hash = hash * multiplier + (contraseña == null ? 0 : contraseña.GetHashCode());
    			hash = hash * multiplier + (telefono == null ? 0 : telefono.GetHashCode());
    
    			return hash;
    	    }
    
    	}
        
        /// <summary>
        /// Compare this object against another instance using a value approach (field-by-field) 
        /// </summary>
        /// <remarks>See http://www.loganfranken.com/blog/687/overriding-equals-in-c-part-1/ for detailed info </remarks>
    	public override bool Equals(object obj)
    	{
    
            if (ReferenceEquals(null, obj)) return false;        // Is Null?
            if (ReferenceEquals(this, obj)) return true;         // Is same object?
            if (obj.GetType() != this.GetType()) return false;   // Is same type?
    	    
            Usuario target = obj as Usuario;
    
    		return true
               &&  (this.usuarioId == target.usuarioId )       
               &&  (this.nombre == target.nombre )       
               &&  (this.apellido1 == target.apellido1 )       
               &&  (this.apellido2 == target.apellido2 )       
               &&  (this.email == target.email )       
               &&  (this.contraseña == target.contraseña )       
               &&  (this.telefono == target.telefono )       
               ;
    
        }
    
    
    	public static bool operator ==(Usuario  objA, Usuario  objB)
        {
            // Check if the objets are the same Usuario entity
            if(Object.ReferenceEquals(objA, objB))
                return true;
      
            return objA.Equals(objB);
    }
    
    
    	public static bool operator !=(Usuario  objA, Usuario  objB)
        {
            return !(objA == objB);
        }
    
    
        /// <summary>
        /// Returns a <see cref="T:System.String"></see> that represents the 
        /// current <see cref="T:System.Object"></see>.
        /// </summary>
        /// <returns>
        /// A <see cref="T:System.String"></see> that represents the current 
        /// <see cref="T:System.Object"></see>.
        /// </returns>
    	public override String ToString()
    	{
    	    StringBuilder strUsuario = new StringBuilder();
    
    		strUsuario.Append("[ ");
           strUsuario.Append(" usuarioId = " + usuarioId + " | " );       
           strUsuario.Append(" nombre = " + nombre + " | " );       
           strUsuario.Append(" apellido1 = " + apellido1 + " | " );       
           strUsuario.Append(" apellido2 = " + apellido2 + " | " );       
           strUsuario.Append(" email = " + email + " | " );       
           strUsuario.Append(" contraseña = " + contraseña + " | " );       
           strUsuario.Append(" telefono = " + telefono + " | " );       
            strUsuario.Append("] ");    
    
    		return strUsuario.ToString();
        }
    
    
    }
}
